default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: postgres
  host: localhost
  database: nuuvem_challenge_development

test:
  <<: *default
  username: postgres
  password: postgres
  host: localhost
  database: nuuvem_challenge_test


production:
  <<: *default
  database: nuuvem_challenge_production
  username: nuuvem_challenge
  password: <%= ENV["NUUVEM_CHALLENGE_DATABASE_PASSWORD"] %>
